class Constant:
    END_NAME = 'game_end'
    VOTE_STAGE_NAME='vote'
    INSOMNIAC_TURN_NAME='insomniac'
    DRUNK_TURN_NAME='drunk'
    TROUBLEMAKER_TURN_NAME='troublemaker'
    ROBBER_TURN_NAME='robber'
    SEER_TURN_NAME='seer'
    MASON_TURN_NAME='mason'
    MINION_TURN_NAME='minion'
    WEREWOLF_TURN_NAME='werewolf'
    DOPPELGANGER_ACTION_TURN_NAME='doppelganger_action'
    DOPPELGANGER_TURN_NAME='doppelganger'
    GAME_START_NAME='game_start'